version: '3'

services:
  research-graph-synthetic:
    build:
      context: .
    stdin_open: true
    tty: true
    image:
      research-graph-synthetic:latest
    volumes:
      # Map src -> app for code updates.
      - ${PWD}/src:/app
